In [1]:
import pandas as pd

C:\Users\Korisnik\pms_for_ml\pms_env\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\Korisnik\pms_for_ml\pms_env\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.2' currently installed).
  from pandas.core import (


In [2]:
file_path = 'C:/Users/Korisnik/Desktop/Database - Master Thesis 2.xlsx'
og_database = pd.read_excel(file_path, sheet_name='Bet 2')

In [3]:
column_names = og_database.columns.tolist()
print(column_names)

['ID', 'Season', 'Matchday', 'Match', 'Date', 'Day of the Week', 'Unnamed: 6', 'Time', 'Home Team', 'Unnamed: 9', 'Away Team', 'Result', 'Full-Time Result', 'Half-Time Result', 'Unnamed: 14', 'Full-Time Home Goals', 'Full-Time Away Goals', 'Unnamed: 17', 'Half-Time Home Goals', 'Half-Time Away Goals', 'Unnamed: 20', 'H Matches Played', 'H Wins', 'H Draws', 'H Losses', 'H Goals', 'H Goal Difference', 'H Points', 'H Goals Scored', 'H Goals Received', 'Unnamed: 30', 'A Matches Played', 'A Wins', 'A Draws', 'A Losses', 'A Goals', 'A Goal Difference', 'A Points', 'A Goals Scored', 'A Goals Received', 'Unnamed: 40', 'H Last Five Wins', 'H Last Five Draws', 'H Last Five Losses', 'H Last Five Goals', 'H Last Five Goal Difference', 'H Last Five Points', 'H Last Five Goals Scored', 'H Last Five Goals Received', 'Unnamed: 49', 'A Last Five Wins', 'A Last Five Draws', 'A Last Five Losses', 'A Last Five Goals', 'A Last Five Goal Difference', 'A Last Five Points', 'A Last Five Goals Scored', 'A Last

In [4]:
selected_columns = ['ID', 'Season', 'Full-Time Result', 'Half-Time Result', 'Full-Time Home Goals', 'Full-Time Away Goals', 'Half-Time Home Goals', 'Half-Time Away Goals', 'H Matches Played', 'H Wins', 'H Draws', 'H Losses', 'H Goals', 'H Goal Difference', 'H Points', 'H Goals Scored', 'H Goals Received','A Matches Played', 'A Wins', 'A Draws', 'A Losses', 'A Goals', 'A Goal Difference', 'A Points', 'A Goals Scored', 'A Goals Received', 'H Last Five Wins', 'H Last Five Draws', 'H Last Five Losses', 'H Last Five Goals', 'H Last Five Goal Difference', 'H Last Five Points', 'H Last Five Goals Scored', 'H Last Five Goals Received', 'A Last Five Wins', 'A Last Five Draws', 'A Last Five Losses', 'A Last Five Goals', 'A Last Five Goal Difference', 'A Last Five Points', 'A Last Five Goals Scored', 'A Last Five Goals Received', 'H Home Matches Played', 'H Home Wins', 'H Home Draws', 'H Home Losses', 'H Home Goals', 'H Home Goal Difference', 'H Home Points', 'H Home Goals Scored', 'H Home Goals Received', 'A Away Matches Played', 'A Away Wins', 'A Away Draws', 'A Away Losses', 'A Away Goals', 'A Away Goal Difference', 'A Away Points', 'A Away Goals Scored', 'A Away Goals Received', 'H Average Age', 'H Foreigners', 'H Average Market Value', 'H Total Market Value', 'H Expenditure', 'H Arrivals', 'H Income', 'H Departures', 'H Balance', 'H Fair Play Points', 'A Average Age', 'A Foreigners', 'A Average Market Value', 'A Total Market Value', 'A Expenditure', 'A Arrivals', 'A Income', 'A Departures', 'A Balance', 'A Fair Play Points', 'Outcome']

In [5]:
db_subset = og_database[selected_columns]

In [6]:
selected_columns_2 = ['H Wins', 'H Losses', 'H Goal Difference', 'A Wins', 'A Losses', 'A Goal Difference', 'H Last Five Wins', 'H Last Five Losses', 'H Last Five Goal Difference', 'A Last Five Wins', 'A Last Five Losses', 'A Last Five Goal Difference', 'H Average Age', 'H Foreigners', 'H Total Market Value', 'H Arrivals', 'H Balance', 'H Fair Play Points', 'A Average Age', 'A Foreigners', 'A Total Market Value', 'A Arrivals', 'A Balance', 'A Fair Play Points', 'Outcome']

In [7]:
db_subset_2 = og_database[selected_columns_2]

In [8]:
train_data = db_subset_2.iloc[1:3240]
test_data = db_subset_2.iloc[3240:]

In [9]:
X_train = train_data.drop(columns=['Outcome'])
y_train = train_data['Outcome']
X_test = test_data.drop(columns=['Outcome'])
y_test = test_data['Outcome']

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
scaler = StandardScaler()

X_train_standardized = scaler.fit_transform(X_train)
X_test_standardized = scaler.transform(X_test)

In [12]:
print(X_train_standardized.mean(axis=0))
print(X_train_standardized.std(axis=0))

[ 6.58113062e-17 -4.38742041e-18 -1.26138337e-17  4.82616245e-17
  4.93584796e-17 -9.32326838e-18 -6.47144511e-17 -4.60679143e-17
 -8.77484082e-18  3.50993633e-17  6.14238858e-17  2.19371021e-18
 -2.58857804e-15  0.00000000e+00  1.75496816e-17  3.50993633e-17
  0.00000000e+00 -2.45695543e-16  1.11879221e-16 -7.01987266e-17
  8.77484082e-17  2.45695543e-16  5.26490449e-17 -1.40397453e-16]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [13]:
import sys
sys.path.append(r'C:\Users\Korisnik\AppData\Roaming\Python\Python39\site-packages')

from statsmodels.stats.outliers_influence import variance_inflation_factor

In [14]:
X_train_df = pd.DataFrame(X_train_standardized, columns=X_train.columns)

vif_data = pd.DataFrame()
vif_data["Feature"] = X_train_df.columns
vif_data["VIF"] = [variance_inflation_factor(X_train_df.values, i) for i in range(X_train_df.shape[1])]

pd.set_option('display.max_rows', None)

print(vif_data)

                        Feature        VIF
0                        H Wins  15.141417
1                      H Losses  15.530162
2             H Goal Difference  13.847113
3                        A Wins  14.950618
4                      A Losses  15.748714
5             A Goal Difference  13.972650
6              H Last Five Wins   4.271602
7            H Last Five Losses   4.345421
8   H Last Five Goal Difference   6.931108
9              A Last Five Wins   4.275923
10           A Last Five Losses   4.180240
11  A Last Five Goal Difference   6.694565
12                H Average Age   1.140251
13                 H Foreigners   2.059405
14         H Total Market Value   3.249814
15                   H Arrivals   2.144508
16                    H Balance   2.489550
17           H Fair Play Points   1.249817
18                A Average Age   1.056489
19                 A Foreigners   2.068543
20         A Total Market Value   3.225628
21                   A Arrivals   2.138309
22         

In [15]:
import numpy as np
import pandas as pd
from sklearn.model_selection import GridSearchCV, cross_val_predict, StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, log_loss, confusion_matrix
from sklearn.metrics import roc_auc_score

In [16]:
models = {
    'Logistic Regression': {
        'model': LogisticRegression(max_iter=500),
        'param_grid': {
            'model__C': [0.1, 1, 10],
            'model__penalty': ['l2']
        }
    },
    'SVM': {
        'model': SVC(probability=True),
        'param_grid': {
            'model__C': [0.1, 1, 10],
            'model__kernel': ['linear', 'rbf'],
            'model__gamma': ['scale']
        }
    },
    'Gradient Boosted Trees': {
        'model': GradientBoostingClassifier(),
        'param_grid': {
            'model__n_estimators': [50, 100],
            'model__learning_rate': [0.01, 0.1],
            'model__max_depth': [3, 5]
        }
    },
    'XGBoost': {
        'model': XGBClassifier(use_label_encoder=False, eval_metric='mlogloss'),
        'param_grid': {
            'model__n_estimators': [50, 100],
            'model__learning_rate': [0.01, 0.1],
            'model__max_depth': [3, 5],
            'model__gamma': [0, 0.1]
        }
    }
}

In [17]:
def nested_cv(X, y, models, outer_cv_folds=5, inner_cv_folds=5):
    results = {}
    
    outer_cv = StratifiedKFold(n_splits=outer_cv_folds, shuffle=True, random_state=42)
    
    for model_name, config in models.items():
        print(f"Processing {model_name}...")
        
        inner_cv = StratifiedKFold(n_splits=inner_cv_folds, shuffle=True, random_state=42)
        
        pipeline = Pipeline([
            ('scaler', StandardScaler()),
            ('model', config['model'])
        ])
        
        grid_search = GridSearchCV(
            estimator=pipeline,
            param_grid=config['param_grid'],
            scoring='accuracy',
            cv=inner_cv,
            n_jobs=-1
        )
        
        y_true, y_pred, y_pred_prob = [], [], []
        
        for train_idx, test_idx in outer_cv.split(X, y):
            X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
            y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
            
            grid_search.fit(X_train, y_train)
            best_model = grid_search.best_estimator_
            
            y_true.extend(y_test)
            y_pred.extend(best_model.predict(X_test))
            y_pred_prob.extend(best_model.predict_proba(X_test)[:, 1])
        
        y_true = np.array(y_true)
        y_pred = np.array(y_pred)
        y_pred_prob = np.array(y_pred_prob)
        
        metrics = {
            'mean_accuracy': accuracy_score(y_true, y_pred),
            'mean_precision': precision_score(y_true, y_pred),
            'mean_recall': recall_score(y_true, y_pred),
            'mean_f1_score': f1_score(y_true, y_pred),
            'mean_roc_auc': roc_auc_score(y_true, y_pred_prob),
            'mean_log_loss': log_loss(y_true, y_pred_prob)
        }
        
        results[model_name] = metrics
    
    return results

In [18]:
X_train = X_train
y_train = train_data['Outcome']

cv_results = nested_cv(X_train, y_train, models)

for model_name, metrics in cv_results.items():
    print(f"{model_name}:")
    for metric_name, metric_value in metrics.items():
        print(f"  {metric_name}: {metric_value:.3f}")

Processing Logistic Regression...
Processing SVM...
Processing Gradient Boosted Trees...
Processing XGBoost...
Logistic Regression:
  mean_accuracy: 0.696
  mean_precision: 0.712
  mean_recall: 0.926
  mean_f1_score: 0.805
  mean_roc_auc: 0.679
  mean_log_loss: 0.588
SVM:
  mean_accuracy: 0.689
  mean_precision: 0.704
  mean_recall: 0.932
  mean_f1_score: 0.802
  mean_roc_auc: 0.658
  mean_log_loss: 0.599
Gradient Boosted Trees:
  mean_accuracy: 0.685
  mean_precision: 0.716
  mean_recall: 0.886
  mean_f1_score: 0.792
  mean_roc_auc: 0.672
  mean_log_loss: 0.594
XGBoost:
  mean_accuracy: 0.692
  mean_precision: 0.714
  mean_recall: 0.909
  mean_f1_score: 0.800
  mean_roc_auc: 0.675
  mean_log_loss: 0.589


In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV, cross_val_score
from sklearn.pipeline import Pipeline
import numpy as np

In [17]:
model = LogisticRegression(solver='liblinear')
pipeline = Pipeline([
    ('model', model)
])

In [18]:
param_grid = {
    'model__C': [0.01, 0.1, 1, 10, 100],
    'model__penalty': ['l2']
}

In [19]:
grid_search = GridSearchCV(estimator=pipeline, param_grid=param_grid, cv=10, scoring='accuracy', n_jobs=-1)

In [20]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=10,
             estimator=Pipeline(steps=[('model',
                                        LogisticRegression(solver='liblinear'))]),
             n_jobs=-1,
             param_grid={'model__C': [0.01, 0.1, 1, 10, 100],
                         'model__penalty': ['l2']},
             scoring='accuracy')

In [21]:
cv_results = grid_search.cv_results_

for mean_score, std_score, params in zip(cv_results['mean_test_score'], cv_results['std_test_score'], cv_results['params']):
    print(f"Mean Accuracy: {mean_score:.3f} ± {std_score:.3f} for {params}")

Mean Accuracy: 0.695 ± 0.024 for {'model__C': 0.01, 'model__penalty': 'l2'}
Mean Accuracy: 0.695 ± 0.024 for {'model__C': 0.1, 'model__penalty': 'l2'}
Mean Accuracy: 0.695 ± 0.024 for {'model__C': 1, 'model__penalty': 'l2'}
Mean Accuracy: 0.695 ± 0.024 for {'model__C': 10, 'model__penalty': 'l2'}
Mean Accuracy: 0.695 ± 0.024 for {'model__C': 100, 'model__penalty': 'l2'}


In [22]:
y_pred = grid_search.best_estimator_.predict(X_test)

In [23]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [24]:
test_accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {test_accuracy:.3f}")

Test Accuracy: 0.656


In [25]:
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[19 45]
 [17 99]]


In [26]:
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Classification Report:
              precision    recall  f1-score   support

           0       0.53      0.30      0.38        64
           1       0.69      0.85      0.76       116

    accuracy                           0.66       180
   macro avg       0.61      0.58      0.57       180
weighted avg       0.63      0.66      0.63       180



In [27]:
predicted_probabilities = grid_search.best_estimator_.predict_proba(X_test)

In [28]:
prob_class_0 = predicted_probabilities[:, 0]

In [29]:
decimal_odds_class_0 = 1 / prob_class_0

In [30]:
for i, odds in enumerate(decimal_odds_class_0):
    print(f"Game {i+1}: Predicted Probability of Class 0: {prob_class_0[i]:.3f}, Decimal Odds for Class 0: {odds:.2f}")

Game 1: Predicted Probability of Class 0: 0.310, Decimal Odds for Class 0: 3.22
Game 2: Predicted Probability of Class 0: 0.402, Decimal Odds for Class 0: 2.49
Game 3: Predicted Probability of Class 0: 0.493, Decimal Odds for Class 0: 2.03
Game 4: Predicted Probability of Class 0: 0.639, Decimal Odds for Class 0: 1.56
Game 5: Predicted Probability of Class 0: 0.538, Decimal Odds for Class 0: 1.86
Game 6: Predicted Probability of Class 0: 0.330, Decimal Odds for Class 0: 3.03
Game 7: Predicted Probability of Class 0: 0.146, Decimal Odds for Class 0: 6.87
Game 8: Predicted Probability of Class 0: 0.348, Decimal Odds for Class 0: 2.88
Game 9: Predicted Probability of Class 0: 0.214, Decimal Odds for Class 0: 4.66
Game 10: Predicted Probability of Class 0: 0.245, Decimal Odds for Class 0: 4.08
Game 11: Predicted Probability of Class 0: 0.460, Decimal Odds for Class 0: 2.17
Game 12: Predicted Probability of Class 0: 0.558, Decimal Odds for Class 0: 1.79
Game 13: Predicted Probability of Cla

In [31]:
prob_class_1 = predicted_probabilities[:, 1]

In [32]:
decimal_odds_class_1 = 1 / prob_class_1

In [33]:
prob_sum = prob_class_0 + prob_class_1

In [34]:
margin = 1.05
adjusted_prob_class_0 = prob_class_0 / prob_sum * margin
adjusted_prob_class_1 = prob_class_1 / prob_sum * margin

In [35]:
odds_class_0 = 1 / adjusted_prob_class_0
odds_class_1 = 1 / adjusted_prob_class_1

In [36]:
for i in range(len(odds_class_0)):
    print(f"Game {i+1}: Adjusted Odds for Class 0: {odds_class_0[i]:.2f}, Adjusted Odds for Class 1: {odds_class_1[i]:.2f}")

Game 1: Adjusted Odds for Class 0: 3.07, Adjusted Odds for Class 1: 1.38
Game 2: Adjusted Odds for Class 0: 2.37, Adjusted Odds for Class 1: 1.59
Game 3: Adjusted Odds for Class 0: 1.93, Adjusted Odds for Class 1: 1.88
Game 4: Adjusted Odds for Class 0: 1.49, Adjusted Odds for Class 1: 2.64
Game 5: Adjusted Odds for Class 0: 1.77, Adjusted Odds for Class 1: 2.06
Game 6: Adjusted Odds for Class 0: 2.88, Adjusted Odds for Class 1: 1.42
Game 7: Adjusted Odds for Class 0: 6.54, Adjusted Odds for Class 1: 1.11
Game 8: Adjusted Odds for Class 0: 2.74, Adjusted Odds for Class 1: 1.46
Game 9: Adjusted Odds for Class 0: 4.44, Adjusted Odds for Class 1: 1.21
Game 10: Adjusted Odds for Class 0: 3.88, Adjusted Odds for Class 1: 1.26
Game 11: Adjusted Odds for Class 0: 2.07, Adjusted Odds for Class 1: 1.76
Game 12: Adjusted Odds for Class 0: 1.71, Adjusted Odds for Class 1: 2.15
Game 13: Adjusted Odds for Class 0: 2.13, Adjusted Odds for Class 1: 1.72
Game 14: Adjusted Odds for Class 0: 1.58, Adjus

In [37]:
from sklearn.metrics import accuracy_score

In [38]:
threshold = 0.5
predicted_outcome = (adjusted_prob_class_0 <= threshold).astype(int)

In [39]:
accuracy = accuracy_score(y_test, predicted_outcome)
print(f"Binary Accuracy: {accuracy:.3f}")

Binary Accuracy: 0.644


In [46]:
import numpy as np
from sklearn.metrics import accuracy_score

xbet_odds = [4.1, 4.12, 2.13, 1.65, 1.75, 5.37, 7.58, 3.4, 6.74, 3.73, 2.31, 1.64,
1.82, 1.94, 1.99, 4.85, 2.83, 5.34, 3.94, 2.3, 2.3, 4.34, 1.59, 1.54,
2.35, 2.66, 6.28, 3.84, 3, 2.55, 3.8, 2.7, 2.67, 2.99, 1.91, 3.33,
3.26, 3.8, 2.22, 2.09, 4.29, 1.88, 2.49, 5.67, 3.32, 2.47, 7.65, 3.2,
6.64, 4.3, 2.79, 2.01, 1.57, 1.99, 1.7, 6.51, 4.85, 3.79, 7.84, 4.87,
1.63, 2, 1.91, 2.95, 2.2, 6.74, 4.23, 8.56, 2.7, 6.56, 1.83, 3.48,
1.99, 3.58, 3.51, 2.49, 4.27, 4.45, 2.67, 6.11, 3.19, 3.06, 2.64, 2.63,
5.7, 1.5, 2.52, 2.35, 4.39, 5.93, 1.37, 3.91, 2.25, 2.64, 1.52, 9.13,
3.06, 3.89, 6.63, 8.04, 1.79, 2.14, 1.61, 1.7, 1.79, 4.02, 7.86, 9.12,
5.14, 3.62, 1.37, 1.61, 1.39, 3.06, 2.7, 2.42, 2.66, 7.11, 4.81, 2.58,
6.09, 3.9, 2.75, 1.55, 2.14, 2.48, 2.08, 2.88, 1.8, 3.05, 1.97, 3.86,
3.33, 7.57, 4.3, 2.3, 6.06, 2.74, 5.68, 10, 1.33, 1.63, 2.6, 1.54,
4.44, 6.91, 7.67, 2.68, 6.89, 4.87, 1.54, 2.2, 2.5, 1.7, 2.05, 3.21,
9.24, 6.22, 7.87, 2.81, 3.1, 1.62, 3.38, 3.16, 3.58, 1.99, 3.56, 4.11,
2.74, 8.01, 4.22, 2.14, 3.76, 4.37, 4.15, 7.33, 1.85, 2.16, 1.65, 4.48]
williamhill_odds = [3.6, 3.7, 2.15, 1.57, 1.73, 5, 8.5, 3.1, 7, 3.4, 2.25, 1.57,
1.8, 1.91, 1.83, 4.8, 2.7, 5.8, 3.2, 2.15, 2.15, 4, 1.6, 1.47,
2.3, 2.6, 6.5, 3.9, 2.8, 2.55, 3.4, 2.62, 2.6, 2.88, 1.91, 3.25,
3.2, 3.3, 2.2, 2.1, 4.33, 1.88, 2.4, 6.5, 3.2, 2.4, 8, 3,
7, 4, 2.6, 1.91, 1.44, 1.8, 1.62, 6, 4.75, 3.6, 7.5, 4.8,
1.5, 1.83, 1.83, 2.7, 2.1, 7, 4.2, 9, 2.5, 6.5, 1.73, 3.25,
1.85, 3.4, 3.25, 2.3, 4.2, 4.4, 2.45, 6, 2.88, 2.88, 2.5, 2.5,
5.5, 1.53, 2.2, 2.25, 3.8, 5.8, 1.25, 4.2, 2.1, 2.45, 1.4, 11,
2.8, 3.6, 7.5, 9, 1.73, 2, 1.5, 1.6, 1.75, 3.8, 9, 11,
5, 3.4, 1.3, 1.44, 1.3, 2.8, 2.6, 2.3, 2.6, 8, 4.5, 2.3,
5.3, 3.4, 2.62, 1.5, 2.05, 2.6, 2, 2.9, 1.83, 3, 1.91, 3.8,
3.25, 9, 4, 2.15, 7, 2.7, 5.5, 12, 1.25, 1.53, 2.5, 1.4,
4.2, 7.5, 9.5, 2.45, 7, 5.5, 1.44, 1.91, 2.3, 1.57, 2, 3,
11, 7, 9, 2.7, 3.1, 1.53, 2.9, 2.8, 3.25, 1.95, 3.6, 4.33,
2.62, 7.5, 4.2, 1.95, 3.75, 5, 3.8, 7.5, 1.85, 2.1, 1.53, 4.4]
actual_outcomes = [1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0,
0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0]

threshold = 2.0

xbet_predictions = [0 if odds < threshold else 1 for odds in xbet_odds]
williamhill_predictions = [0 if odds < threshold else 1 for odds in williamhill_odds]

xbet_accuracy = accuracy_score(actual_outcomes, xbet_predictions)
williamhill_accuracy = accuracy_score(actual_outcomes, williamhill_predictions)

print(f"XBet Accuracy: {xbet_accuracy:.2f}")
print(f"WilliamHill Accuracy: {williamhill_accuracy:.2f}")

XBet Accuracy: 0.66
WilliamHill Accuracy: 0.66


In [47]:
import numpy as np
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

xbet_odds = [4.1, 4.12, 2.13, 1.65, 1.75, 5.37, 7.58, 3.4, 6.74, 3.73, 2.31, 1.64,
1.82, 1.94, 1.99, 4.85, 2.83, 5.34, 3.94, 2.3, 2.3, 4.34, 1.59, 1.54,
2.35, 2.66, 6.28, 3.84, 3, 2.55, 3.8, 2.7, 2.67, 2.99, 1.91, 3.33,
3.26, 3.8, 2.22, 2.09, 4.29, 1.88, 2.49, 5.67, 3.32, 2.47, 7.65, 3.2,
6.64, 4.3, 2.79, 2.01, 1.57, 1.99, 1.7, 6.51, 4.85, 3.79, 7.84, 4.87,
1.63, 2, 1.91, 2.95, 2.2, 6.74, 4.23, 8.56, 2.7, 6.56, 1.83, 3.48,
1.99, 3.58, 3.51, 2.49, 4.27, 4.45, 2.67, 6.11, 3.19, 3.06, 2.64, 2.63,
5.7, 1.5, 2.52, 2.35, 4.39, 5.93, 1.37, 3.91, 2.25, 2.64, 1.52, 9.13,
3.06, 3.89, 6.63, 8.04, 1.79, 2.14, 1.61, 1.7, 1.79, 4.02, 7.86, 9.12,
5.14, 3.62, 1.37, 1.61, 1.39, 3.06, 2.7, 2.42, 2.66, 7.11, 4.81, 2.58,
6.09, 3.9, 2.75, 1.55, 2.14, 2.48, 2.08, 2.88, 1.8, 3.05, 1.97, 3.86,
3.33, 7.57, 4.3, 2.3, 6.06, 2.74, 5.68, 10, 1.33, 1.63, 2.6, 1.54,
4.44, 6.91, 7.67, 2.68, 6.89, 4.87, 1.54, 2.2, 2.5, 1.7, 2.05, 3.21,
9.24, 6.22, 7.87, 2.81, 3.1, 1.62, 3.38, 3.16, 3.58, 1.99, 3.56, 4.11,
2.74, 8.01, 4.22, 2.14, 3.76, 4.37, 4.15, 7.33, 1.85, 2.16, 1.65, 4.48]
williamhill_odds = [3.6, 3.7, 2.15, 1.57, 1.73, 5, 8.5, 3.1, 7, 3.4, 2.25, 1.57,
1.8, 1.91, 1.83, 4.8, 2.7, 5.8, 3.2, 2.15, 2.15, 4, 1.6, 1.47,
2.3, 2.6, 6.5, 3.9, 2.8, 2.55, 3.4, 2.62, 2.6, 2.88, 1.91, 3.25,
3.2, 3.3, 2.2, 2.1, 4.33, 1.88, 2.4, 6.5, 3.2, 2.4, 8, 3,
7, 4, 2.6, 1.91, 1.44, 1.8, 1.62, 6, 4.75, 3.6, 7.5, 4.8,
1.5, 1.83, 1.83, 2.7, 2.1, 7, 4.2, 9, 2.5, 6.5, 1.73, 3.25,
1.85, 3.4, 3.25, 2.3, 4.2, 4.4, 2.45, 6, 2.88, 2.88, 2.5, 2.5,
5.5, 1.53, 2.2, 2.25, 3.8, 5.8, 1.25, 4.2, 2.1, 2.45, 1.4, 11,
2.8, 3.6, 7.5, 9, 1.73, 2, 1.5, 1.6, 1.75, 3.8, 9, 11,
5, 3.4, 1.3, 1.44, 1.3, 2.8, 2.6, 2.3, 2.6, 8, 4.5, 2.3,
5.3, 3.4, 2.62, 1.5, 2.05, 2.6, 2, 2.9, 1.83, 3, 1.91, 3.8,
3.25, 9, 4, 2.15, 7, 2.7, 5.5, 12, 1.25, 1.53, 2.5, 1.4,
4.2, 7.5, 9.5, 2.45, 7, 5.5, 1.44, 1.91, 2.3, 1.57, 2, 3,
11, 7, 9, 2.7, 3.1, 1.53, 2.9, 2.8, 3.25, 1.95, 3.6, 4.33,
2.62, 7.5, 4.2, 1.95, 3.75, 5, 3.8, 7.5, 1.85, 2.1, 1.53, 4.4]
actual_outcomes = [1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0]

threshold = 2.0

xbet_predictions = [0 if odds < threshold else 1 for odds in xbet_odds]
williamhill_predictions = [0 if odds < threshold else 1 for odds in williamhill_odds]

xbet_confusion_matrix = confusion_matrix(actual_outcomes, xbet_predictions)
williamhill_confusion_matrix = confusion_matrix(actual_outcomes, williamhill_predictions)

ConfusionMatrixDisplay(xbet_confusion_matrix, display_labels=[0, 1]).plot()
ConfusionMatrixDisplay(williamhill_confusion_matrix, display_labels=[0, 1]).plot()

print("XBet Confusion Matrix:")
print(xbet_confusion_matrix)
print("\nWilliamHill Confusion Matrix:")
print(williamhill_confusion_matrix)

XBet Confusion Matrix:
[[21 43]
 [18 98]]

WilliamHill Confusion Matrix:
[[23 41]
 [20 96]]


In [48]:
import numpy as np
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

my_odds = [3.07, 2.37, 1.93, 1.49, 1.77, 2.88, 6.54, 2.74, 4.44, 3.88, 2.07, 1.71,
2.13, 1.58, 1.91, 5.34, 2.58, 4.00, 5.53, 2.24, 2.33, 2.69, 1.67, 1.44,
2.04, 1.90, 2.96, 3.57, 4.06, 2.37, 3.17, 2.22, 2.32, 2.54, 1.83, 2.43,
2.61, 2.89, 2.17, 2.07, 3.00, 1.98, 1.86, 5.34, 3.12, 2.25, 5.74, 2.20,
4.15, 4.58, 2.61, 1.96, 1.64, 1.96, 1.46, 5.14, 3.09, 2.91, 6.32, 3.06,
1.74, 1.90, 1.68, 2.37, 2.13, 4.54, 2.79, 4.29, 1.95, 6.80, 1.88, 2.84,
1.63, 2.98, 3.18, 2.30, 2.51, 2.53, 2.80, 4.53, 2.83, 2.31, 2.57, 2.44,
3.92, 1.82, 2.11, 1.65, 2.76, 6.07, 1.77, 3.07, 1.93, 2.37, 1.49, 6.54,
2.74, 2.88, 3.88, 4.44, 1.91, 2.07, 1.71, 2.13, 1.58, 2.58, 5.34, 5.53,
4.00, 2.24, 1.67, 1.44, 2.04, 2.69, 2.33, 1.90, 4.06, 3.57, 2.96, 2.37,
3.17, 2.54, 2.32, 1.83, 2.22, 2.61, 2.43, 2.17, 2.07, 2.89, 1.98, 3.00,
1.86, 5.34, 3.12, 2.25, 4.15, 2.20, 4.58, 5.74, 1.46, 1.64, 1.96, 1.96,
2.61, 3.09, 5.14, 2.91, 6.32, 3.06, 1.74, 1.68, 2.13, 1.90, 2.37, 1.95,
6.80, 4.29, 4.54, 2.79, 2.98, 1.63, 3.18, 1.88, 2.84, 2.30, 2.53, 2.80,
2.51, 4.53, 2.44, 2.83, 2.57, 3.92, 2.31, 2.11, 2.76, 1.82, 1.65, 6.07]
actual_outcomes = [1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0]

threshold = 2.0

my_odds_predictions = [0 if odds < threshold else 1 for odds in my_odds]

my_odds_confusion_matrix = confusion_matrix(actual_outcomes, my_odds_predictions)

ConfusionMatrixDisplay(my_odds_confusion_matrix, display_labels=[0, 1]).plot()

print("My Odds Confusion Matrix:")
print(my_odds_confusion_matrix)

My Odds Confusion Matrix:
[[24 40]
 [24 92]]
